---
ansible_python_interpreter: /usr/bin/python3
install_cadvisor_exporter: false
install_nginx_exporter: false
install_redis_exporter: false
users:
  - username: forge
    oh_my_zsh:
      theme: robbyrussell
  - username: root
    oh_my_zsh:
      theme: robbyrussell
custom_firewall_ports:
  - 9100  # node exporter
  - 9191  # fail2ban exporter
