---
- name: Install & configure mysql server
  hosts: all
  vars:
    custom_firewall_ports:
      - 111
      - 2049
      - 3306
      - 6379
    apt_packages:
      - nfs-kernel-server
    install_redis_exporter: true
    install_mysqld_exporter: true
    description: 'database & filestorage node for hosting app.retailor.io'
  roles:
    - role: roles/firewall
    - role: roles/mysql
