---
- name: Create a Docker network for Elasticsearch
  docker_network:
    name: elk_network
    state: present
    driver: bridge
    ipam_config:
      - subnet: "172.19.0.0/16"
        gateway: "172.19.0.1"
        iprange: "172.19.0.0/24"

