---
- name: Assert supported distribution
  ansible.builtin.include_tasks: check_distro.yml
  tags:
    - docker_check_distro

- name: Install Docker
  ansible.builtin.include_tasks: install.yml
  when: docker_distro_supported
  tags:
    - docker_install

- name: Configure Docker group membership
  ansible.builtin.include_tasks: users.yml
  when: docker_distro_supported and docker_users | length > 0
  tags:
    - docker_users

- name: Manage Docker service
  ansible.builtin.include_tasks: service.yml
  when: docker_distro_supported
  tags:
    - docker_service
